from platform import python_implementation
if python_implementation() == 'PyPy':
    raise ImportError('PyPy not supported yet')
else:
    from _nanomsg import *

#Constants ripped from c headers

NN_MSG = -1 # does this work?
AF_SP = 1
AF_SP_RAW = 2
NN_PROTO_BUS = 7
NN_BUS = (NN_PROTO_BUS * 16 + 0)
NN_INPROC = -1
NN_IPC = -2
NN_VERSION_CURRENT = 0
NN_VERSION_REVISION = 0
NN_VERSION_AGE = 0
NN_SOCKADDR_MAX = 128
NN_SOL_SOCKET = 0
NN_LINGER = 1
NN_SNDBUF = 2
NN_RCVBUF = 3
NN_SNDTIMEO = 4
NN_RCVTIMEO = 5
NN_RECONNECT_IVL = 6
NN_RECONNECT_IVL_MAX = 7
NN_SNDPRIO = 8
NN_SNDFD = 10
NN_RCVFD = 11
NN_DOMAIN = 12
NN_PROTOCOL = 13
NN_IPV4ONLY = 14
NN_DONTWAIT = 1
NN_PROTO_PAIR = 1
NN_PAIR = (NN_PROTO_PAIR * 16 + 0)
NN_PROTO_PIPELINE = 5
NN_PUSH = (NN_PROTO_PIPELINE * 16 + 0)
NN_PULL = (NN_PROTO_PIPELINE * 16 + 1)
NN_PROTO_PUBSUB = 2
NN_PUB = (NN_PROTO_PUBSUB * 16 + 0)
NN_SUB = (NN_PROTO_PUBSUB * 16 + 1)
NN_SUB_SUBSCRIBE = 1
NN_SUB_UNSUBSCRIBE = 2
NN_PROTO_REQREP = 3
NN_REQ = (NN_PROTO_REQREP * 16 + 0)
NN_REP = (NN_PROTO_REQREP * 16 + 1)
NN_REQ_RESEND_IVL = 1
NN_PROTO_SURVEY = 6
NN_SURVEYOR = (NN_PROTO_SURVEY * 16 + 0)
NN_RESPONDENT = (NN_PROTO_SURVEY * 16 + 1)
NN_SURVEYOR_DEADLINE = 1
NN_TCP = -3
NN_TCP_NODELAY = 1
